In [6]:
import numpy as np 
import pandas as pd

In [7]:
train = pd.read_csv("ml-ai-hackathon-2026/train_games.csv")
test = pd.read_csv("ml-ai-hackathon-2026/test_features.csv")

genre = pd.read_csv("ml-ai-hackathon-2026/genre_summary.csv")
platform = pd.read_csv("ml-ai-hackathon-2026/platform_summary.csv")
publisher = pd.read_csv("ml-ai-hackathon-2026/publisher_summary.csv")
yearly = pd.read_csv("ml-ai-hackathon-2026/yearly_trends.csv")

In [8]:
train.shape

(40000, 34)

In [9]:
train.head()

,game_id,title,platform,platform_type,platform_maker,platform_generation,genre,year,publisher,developer,...,game_pass_available,vr_support,goty_nominated,goty_won,how_long_to_beat_main_hrs,how_long_to_beat_completionist_hrs,publisher_is_developer,internal_build_id,marketing_campaign_type,day_one_patch_size_mb
0,G000019,Night in the Saga,Atari 2600,Console,Atari,2,Adventure,1985,Take-Two Interactive,Raw Fury,...,0,0,0,0,16.5,72.7,0,E571DCF3,NaN,7534
1,G000129,Metal Gear Legend,Atari 2600,Console,Atari,2,Idle/Clicker,1985,Nintendo,Larian Studios,...,0,0,0,0,10.6,44.5,0,DA796E03,Campaign_C,13313
2,G000192,FIFA 2024,NES,Console,Nintendo,3,Sports,1985,FromSoftware,Activision Blizzard,...,0,0,0,0,14.0,63.1,0,7C30DA4B,Campaign_C,11487
3,G000200,Tales of World,NES,Console,Nintendo,3,Role-Playing,1985,Ubisoft,Toby Fox,...,0,0,0,0,66.2,152.1,0,D75B1F62,NaN,12498
4,G000254,God of Shadow,PC,PC,Various,0,Action,1985,Nintendo,Nintendo,...,0,0,0,0,10.4,27.4,1,049CF258,Campaign_B,1917

In [10]:
train.publisher_tier

0        AAA
1        AAA
2        AAA
3        AAA
4        AAA
        ...
39995    AAA
39996    AAA
39997    AAA
39998    AAA
39999     AA
Name: publisher_tier, Length: 40000, dtype: str

In [11]:
publisher.shape

(51, 8)

In [12]:
publisher.head(10)

,publisher,publisher_tier,titles,avg_estimated_revenue_million_usd,avg_metacritic_score,avg_user_score,avg_launch_price_usd,pct_sequel
0,2K Games,AAA,1203,822.521671,75.834215,7.595432,45.095605,0.404821
1,505 Games,AA,564,170.252996,68.025676,6.873583,41.494612,0.393617
2,Activision Blizzard,AAA,1175,790.378817,75.370783,7.559883,45.086469,0.414468
3,Annapurna Interactive,Indie,247,62.848057,71.267194,7.206517,40.280486,0.421053
4,Bandai Namco,AAA,1284,871.279276,75.470130,7.580445,45.565369,0.436916
5,Bethesda Softworks,AAA,1226,768.091395,75.206947,7.541353,45.907440,0.427406
6,Bungie,AAA,1177,737.242583,75.573111,7.561939,44.727420,0.419711
7,CD Projekt,AAA,1157,774.453362,75.686414,7.562687,44.808161,0.403630
8,Capcom,AAA,1187,936.382536,75.748202,7.581460,44.454225,0.408593
9,Chucklefish,Indie,225,73.576844,72.653920,7.194985,38.970773,0.493333

In [13]:
publisher.info()

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 8 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   publisher                          51 non-null     str
 1   publisher_tier                     51 non-null     str
 2   titles                             51 non-null     int64
 3   avg_estimated_revenue_million_usd  51 non-null     float64
 4   avg_metacritic_score               51 non-null     float64
 5   avg_user_score                     51 non-null     float64
 6   avg_launch_price_usd               51 non-null     float64
 7   pct_sequel                         51 non-null     float64
dtypes: float64(5), int64(1), str(2)
memory usage: 3.3 KB

In [14]:
publisher["publisher"].duplicated().sum()

np.int64(0)

In [15]:
for col in train.columns.intersection(publisher.columns):
    print(col)
    print("train unique:", train[col].nunique())
    print("publisher unique:", publisher[col].nunique())
    print("-" * 30)

publisher
train unique: 51
publisher unique: 51
------------------------------
publisher_tier
train unique: 3
publisher unique: 3
------------------------------

In [16]:
def check_merge_key(df, key):
    dupes = df[key].duplicated().sum()

    if dupes == 0:
        print(f"✅ '{key}' is unique")
    else:
        print(f"⚠️ '{key}' has {dupes} duplicate rows")

In [17]:
check_merge_key(publisher,"publisher_tier")

⚠️ 'publisher_tier' has 48 duplicate rows

In [18]:
publisher.duplicated(
    subset=["publisher", "publisher_tier"]
).sum()

np.int64(0)

In [19]:
train = train.merge(
    publisher,
    on=["publisher", "publisher_tier"],
    how="left"
)

In [20]:
train.shape

(40000, 40)

In [21]:
for col in train.columns.intersection(platform.columns):
    print(col)
    print("train unique:", train[col].nunique())
    print("platform unique:", platform[col].nunique())
    print("-"*30)

platform
train unique: 30
platform unique: 30
------------------------------
platform_generation
train unique: 9
platform unique: 9
------------------------------
titles
train unique: 48
platform unique: 29
------------------------------
avg_estimated_revenue_million_usd
train unique: 51
platform unique: 29
------------------------------
avg_metacritic_score
train unique: 51
platform unique: 30
------------------------------
avg_user_score
train unique: 51
platform unique: 30
------------------------------
avg_launch_price_usd
train unique: 51
platform unique: 30
------------------------------

In [22]:
check_merge_key(platform,"platform")
check_merge_key(platform,"platform_generation")

✅ 'platform' is unique
⚠️ 'platform_generation' has 21 duplicate rows

In [23]:
platform.duplicated(
    subset=["platform","platform_generation"]
).sum()

np.int64(0)

In [24]:
train = train.merge(platform,
           on=["platform","platform_generation"],
           how = "left")

In [25]:
train.shape

(40000, 46)

In [26]:
train.iloc[:8,40:]

,titles_y,avg_estimated_revenue_million_usd_y,avg_metacritic_score_y,avg_user_score_y,avg_launch_price_usd_y,pct_online_multiplayer
0,1607,936.901307,75.291523,7.514181,59.705971,0.504667
1,1607,936.901307,75.291523,7.514181,59.705971,0.504667
2,3045,874.322355,74.254121,7.419198,60.098635,0.523153
3,3045,874.322355,74.254121,7.419198,60.098635,0.523153
4,4939,352.876064,74.264511,7.417108,32.715224,0.510630
5,4939,352.876064,74.264511,7.417108,32.715224,0.510630
6,3045,874.322355,74.254121,7.419198,60.098635,0.523153
7,1607,936.901307,75.291523,7.514181,59.705971,0.504667

In [27]:
train.columns

Index(['game_id', 'title', 'platform', 'platform_type', 'platform_maker',
       'platform_generation', 'genre', 'year', 'publisher', 'developer',
       'publisher_region', 'publisher_tier', 'esrb_rating', 'metacritic_score',
       'user_score', 'critic_review_count', 'user_review_count',
       'estimated_revenue_million_usd', 'launch_price_usd', 'is_sequel',
       'online_multiplayer', 'dlc_released', 'microtransactions', 'loot_boxes',
       'game_pass_available', 'vr_support', 'goty_nominated', 'goty_won',
       'how_long_to_beat_main_hrs', 'how_long_to_beat_completionist_hrs',
       'publisher_is_developer', 'internal_build_id',
       'marketing_campaign_type', 'day_one_patch_size_mb', 'titles_x',
       'avg_estimated_revenue_million_usd_x', 'avg_metacritic_score_x',
       'avg_user_score_x', 'avg_launch_price_usd_x', 'pct_sequel', 'titles_y',
       'avg_estimated_revenue_million_usd_y', 'avg_metacritic_score_y',
       'avg_user_score_y', 'avg_launch_price_usd_y', 'pct_online_multiplayer'],
      dtype='str')

In [28]:
genre.info()

<class 'pandas.DataFrame'>
RangeIndex: 138 entries, 0 to 137
Data columns (total 10 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   genre                              138 non-null    str
 1   platform_type                      138 non-null    str
 2   titles                             138 non-null    int64
 3   avg_estimated_revenue_million_usd  138 non-null    float64
 4   avg_metacritic_score               137 non-null    float64
 5   avg_user_score                     138 non-null    float64
 6   avg_launch_price_usd               138 non-null    float64
 7   pct_online_multiplayer             138 non-null    float64
 8   pct_dlc_released                   138 non-null    float64
 9   pct_microtransactions              138 non-null    float64
dtypes: float64(7), int64(1), str(2)
memory usage: 10.9 KB

In [29]:
check_merge_key(genre,"genre")

⚠️ 'genre' has 118 duplicate rows

In [30]:
check_merge_key(genre,"platform_type")

⚠️ 'platform_type' has 131 duplicate rows

In [31]:
genre.duplicated(
    subset=["genre","platform_type"]
).sum()

np.int64(0)

In [32]:
train = train.merge(
    genre,
    on=["genre", "platform_type"],
    how="left"
)

In [33]:
train

,game_id,title,platform,platform_type,platform_maker,platform_generation,genre,year,publisher,developer,...,avg_launch_price_usd_y,pct_online_multiplayer_x,titles,avg_estimated_revenue_million_usd,avg_metacritic_score,avg_user_score,avg_launch_price_usd,pct_online_multiplayer_y,pct_dlc_released,pct_microtransactions
0,G000019,Night in the Saga,Atari 2600,Console,Atari,2,Adventure,1985,Take-Two Interactive,Raw Fury,...,59.705971,0.504667,1018,620.544735,76.364855,7.651621,60.210118,0.337917,0.627701,0.233792
1,G000129,Metal Gear Legend,Atari 2600,Console,Atari,2,Idle/Clicker,1985,Nintendo,Larian Studios,...,59.705971,0.504667,207,530.745894,73.528988,7.404522,59.216965,0.338164,0.632850,0.256039
2,G000192,FIFA 2024,NES,Console,Nintendo,3,Sports,1985,FromSoftware,Activision Blizzard,...,60.098635,0.523153,2339,1685.637845,70.982827,7.119449,60.065373,1.000000,0.639590,0.322788
3,G000200,Tales of World,NES,Console,Nintendo,3,Role-Playing,1985,Ubisoft,Toby Fox,...,60.098635,0.523153,1791,904.692217,77.474991,7.745751,59.801496,0.288107,0.634841,0.248465
4,G000254,God of Shadow,PC,PC,Various,0,Action,1985,Nintendo,Nintendo,...,32.715224,0.510630,761,351.012523,73.714104,7.409703,32.997056,0.295664,0.626807,0.231275
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39995,G039739,Apex: Uprising,Xbox One,Console,Microsoft,8,Shooter,2019,Sega,Square Enix,...,59.983224,0.509583,2023,1247.518828,74.222450,7.438646,60.318647,1.000000,0.625309,0.335146
39996,G039846,Gone Home Origins,Stadia,Streaming,Google,9,Adventure,2019,Nintendo,Nintendo,...,7.707347,0.552632,7,0.000000,75.985170,7.716429,6.595026,0.285714,0.714286,0.285714
39997,G039849,Madden NFL 2025,Browser,Browser,Various,0,Sports,2019,2K Games,Devolver Digital,...,-0.001256,0.494563,259,0.000000,71.139071,7.068315,0.065676,1.000000,0.583012,0.405405
39998,G039860,Halo 2,Mobile (iOS),Mobile,Apple,0,Action,2019,2K Games,2K Games,...,2.229225,0.496035,420,193.212643,74.085411,7.423656,2.364155,0.276190,0.638095,0.288095
39999,G039875,Roblox 3,Mobile (Android),Mobile,Google,0,Sandbox,2019,Devolver Digital,Team17,...,2.180591,0.500836,28,512.803214,78.032687,7.392526,1.752242,0.285714,0.535714,0.214286

In [34]:
yearly.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 7 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   year                               700 non-null    int64
 1   genre                              700 non-null    str
 2   titles                             700 non-null    int64
 3   avg_estimated_revenue_million_usd  700 non-null    float64
 4   avg_metacritic_score               700 non-null    float64
 5   avg_user_score                     700 non-null    float64
 6   avg_launch_price_usd               700 non-null    float64
dtypes: float64(4), int64(2), str(1)
memory usage: 38.4 KB

In [35]:
for col in train.columns.intersection(yearly.columns):
    print(col)
    print("train unique:", train[col].nunique())
    print("yearly unique:", yearly[col].nunique())
    print("-" * 30)

genre
train unique: 20
yearly unique: 20
------------------------------
year
train unique: 35
yearly unique: 35
------------------------------
titles
train unique: 109
yearly unique: 164
------------------------------
avg_estimated_revenue_million_usd
train unique: 101
yearly unique: 700
------------------------------
avg_metacritic_score
train unique: 137
yearly unique: 700
------------------------------
avg_user_score
train unique: 138
yearly unique: 700
------------------------------
avg_launch_price_usd
train unique: 138
yearly unique: 700
------------------------------

In [36]:
yearly.duplicated(
    subset=["year","genre"]
).sum()

np.int64(0)

In [37]:
print(train.columns.tolist())

['game_id', 'title', 'platform', 'platform_type', 'platform_maker', 'platform_generation', 'genre', 'year', 'publisher', 'developer', 'publisher_region', 'publisher_tier', 'esrb_rating', 'metacritic_score', 'user_score', 'critic_review_count', 'user_review_count', 'estimated_revenue_million_usd', 'launch_price_usd', 'is_sequel', 'online_multiplayer', 'dlc_released', 'microtransactions', 'loot_boxes', 'game_pass_available', 'vr_support', 'goty_nominated', 'goty_won', 'how_long_to_beat_main_hrs', 'how_long_to_beat_completionist_hrs', 'publisher_is_developer', 'internal_build_id', 'marketing_campaign_type', 'day_one_patch_size_mb', 'titles_x', 'avg_estimated_revenue_million_usd_x', 'avg_metacritic_score_x', 'avg_user_score_x', 'avg_launch_price_usd_x', 'pct_sequel', 'titles_y', 'avg_estimated_revenue_million_usd_y', 'avg_metacritic_score_y', 'avg_user_score_y', 'avg_launch_price_usd_y', 'pct_online_multiplayer_x', 'titles', 'avg_estimated_revenue_million_usd', 'avg_metacritic_score', 'avg_user_score', 'avg_launch_price_usd', 'pct_online_multiplayer_y', 'pct_dlc_released', 'pct_microtransactions']

In [38]:
print(yearly.columns.tolist())

['year', 'genre', 'titles', 'avg_estimated_revenue_million_usd', 'avg_metacritic_score', 'avg_user_score', 'avg_launch_price_usd']

In [39]:
print(train["year"].dtype)
print(yearly["year"].dtype)

int64
int64

In [40]:
set(yearly.columns) - set(train.columns)

set()

No need to merge yearly

In [41]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 54 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   game_id                              40000 non-null  str
 1   title                                40000 non-null  str
 2   platform                             40000 non-null  str
 3   platform_type                        40000 non-null  str
 4   platform_maker                       40000 non-null  str
 5   platform_generation                  40000 non-null  int64
 6   genre                                40000 non-null  str
 7   year                                 40000 non-null  int64
 8   publisher                            40000 non-null  str
 9   developer                            40000 non-null  str
 10  publisher_region                     40000 non-null  str
 11  publisher_tier                       40000 non-null  str
 12  esrb_rating                          40000 non-null  str
 13  metacritic_score                     34000 non-null  float64
 14  user_score                           40000 non-null  float64
 15  critic_review_count                  34000 non-null  float64
 16  user_review_count                    34000 non-null  float64
 17  estimated_revenue_million_usd        40000 non-null  float64
 18  launch_price_usd                     40000 non-null  float64
 19  is_sequel                            40000 non-null  int64
 20  online_multiplayer                   40000 non-null  int64
 21  dlc_released                         40000 non-null  int64
 22  microtransactions                    40000 non-null  int64
 23  loot_boxes                           40000 non-null  int64
 24  game_pass_available                  40000 non-null  int64
 25  vr_support                           40000 non-null  int64
 26  goty_nominated                       40000 non-null  int64
 27  goty_won                             40000 non-null  int64
 28  how_long_to_beat_main_hrs            40000 non-null  float64
 29  how_long_to_beat_completionist_hrs   40000 non-null  float64
 30  publisher_is_developer               40000 non-null  int64
 31  internal_build_id                    40000 non-null  str
 32  marketing_campaign_type              30005 non-null  str
 33  day_one_patch_size_mb                40000 non-null  int64
 34  titles_x                             40000 non-null  int64
 35  avg_estimated_revenue_million_usd_x  40000 non-null  float64
 36  avg_metacritic_score_x               40000 non-null  float64
 37  avg_user_score_x                     40000 non-null  float64
 38  avg_launch_price_usd_x               40000 non-null  float64
 39  pct_sequel                           40000 non-null  float64
 40  titles_y                             40000 non-null  int64
 41  avg_estimated_revenue_million_usd_y  40000 non-null  float64
 42  avg_metacritic_score_y               40000 non-null  float64
 43  avg_user_score_y                     40000 non-null  float64
 44  avg_launch_price_usd_y               40000 non-null  float64
 45  pct_online_multiplayer_x             40000 non-null  float64
 46  titles                               40000 non-null  int64
 47  avg_estimated_revenue_million_usd    40000 non-null  float64
 48  avg_metacritic_score                 39999 non-null  float64
 49  avg_user_score                       40000 non-null  float64
 50  avg_launch_price_usd                 40000 non-null  float64
 51  pct_online_multiplayer_y             40000 non-null  float64
 52  pct_dlc_released                     40000 non-null  float64
 53  pct_microtransactions                40000 non-null  float64
dtypes: float64(25), int64(16), str(13)
memory usage: 16.5 MB

In [42]:
train[['titles_x',
       'titles_y',
       'titles']].head()

   titles_x  titles_y  titles
0      1245      1607    1018
1      1229      1607     207
2      1281      3045    2339
3      1197      3045    1791
4      1229      4939     761

In [43]:
print(publisher.columns)
print(platform.columns)
print(genre.columns)

Index(['publisher', 'publisher_tier', 'titles',
       'avg_estimated_revenue_million_usd', 'avg_metacritic_score',
       'avg_user_score', 'avg_launch_price_usd', 'pct_sequel'],
      dtype='str')
Index(['platform', 'platform_generation', 'titles',
       'avg_estimated_revenue_million_usd', 'avg_metacritic_score',
       'avg_user_score', 'avg_launch_price_usd', 'pct_online_multiplayer'],
      dtype='str')
Index(['genre', 'platform_type', 'titles', 'avg_estimated_revenue_million_usd',
       'avg_metacritic_score', 'avg_user_score', 'avg_launch_price_usd',
       'pct_online_multiplayer', 'pct_dlc_released', 'pct_microtransactions'],
      dtype='str')

In [44]:
rename_dict = {
    # Titles
    'titles_x': 'publisher_titles',
    'titles_y': 'platform_titles',
    'titles': 'genre_titles',

    # Revenue average
    'avg_estimated_revenue_million_usd_x': 'publisher_avg_revenue',
    'avg_estimated_revenue_million_usd_y': 'platform_avg_revenue',
    'avg_estimated_revenue_million_usd': 'genre_avg_revenue',

    # Metacritic scores
    'avg_metacritic_score_x': 'publisher_avg_metacritic_score',
    'avg_metacritic_score_y': 'platform_avg_metacritic_score',
    'avg_metacritic_score': 'genre_avg_metacritic_score',

    # User scores
    'avg_user_score_x': 'publisher_avg_user_score',
    'avg_user_score_y': 'platform_avg_user_score',
    'avg_user_score': 'genre_avg_user_score',

    # Launch prices
    'avg_launch_price_usd_x': 'publisher_avg_launch_price_usd',
    'avg_launch_price_usd_y': 'platform_avg_launch_price_usd',
    'avg_launch_price_usd': 'genre_avg_launch_price_usd',

    # Percentages
    'pct_sequel': 'publisher_pct_sequel',
    'pct_online_multiplayer_x': 'platform_pct_online_multiplayer',
    'pct_online_multiplayer_y': 'genre_pct_online_multiplayer',
    'pct_dlc_released': 'genre_pct_dlc_released',
    'pct_microtransactions': 'genre_pct_microtransactions'
}

train.rename(columns=rename_dict, inplace=True)

In [45]:
[col for col in train.columns if 'publisher_' in col]

['publisher_region',
 'publisher_tier',
 'publisher_is_developer',
 'publisher_titles',
 'publisher_avg_revenue',
 'publisher_avg_metacritic_score',
 'publisher_avg_user_score',
 'publisher_avg_launch_price_usd',
 'publisher_pct_sequel']

In [46]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 54 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   game_id                             40000 non-null  str
 1   title                               40000 non-null  str
 2   platform                            40000 non-null  str
 3   platform_type                       40000 non-null  str
 4   platform_maker                      40000 non-null  str
 5   platform_generation                 40000 non-null  int64
 6   genre                               40000 non-null  str
 7   year                                40000 non-null  int64
 8   publisher                           40000 non-null  str
 9   developer                           40000 non-null  str
 10  publisher_region                    40000 non-null  str
 11  publisher_tier                      40000 non-null  str
 12  esrb_rating                         40000 non-null  str
 13  metacritic_score                    34000 non-null  float64
 14  user_score                          40000 non-null  float64
 15  critic_review_count                 34000 non-null  float64
 16  user_review_count                   34000 non-null  float64
 17  estimated_revenue_million_usd       40000 non-null  float64
 18  launch_price_usd                    40000 non-null  float64
 19  is_sequel                           40000 non-null  int64
 20  online_multiplayer                  40000 non-null  int64
 21  dlc_released                        40000 non-null  int64
 22  microtransactions                   40000 non-null  int64
 23  loot_boxes                          40000 non-null  int64
 24  game_pass_available                 40000 non-null  int64
 25  vr_support                          40000 non-null  int64
 26  goty_nominated                      40000 non-null  int64
 27  goty_won                            40000 non-null  int64
 28  how_long_to_beat_main_hrs           40000 non-null  float64
 29  how_long_to_beat_completionist_hrs  40000 non-null  float64
 30  publisher_is_developer              40000 non-null  int64
 31  internal_build_id                   40000 non-null  str
 32  marketing_campaign_type             30005 non-null  str
 33  day_one_patch_size_mb               40000 non-null  int64
 34  publisher_titles                    40000 non-null  int64
 35  publisher_avg_revenue               40000 non-null  float64
 36  publisher_avg_metacritic_score      40000 non-null  float64
 37  publisher_avg_user_score            40000 non-null  float64
 38  publisher_avg_launch_price_usd      40000 non-null  float64
 39  publisher_pct_sequel                40000 non-null  float64
 40  platform_titles                     40000 non-null  int64
 41  platform_avg_revenue                40000 non-null  float64
 42  platform_avg_metacritic_score       40000 non-null  float64
 43  platform_avg_user_score             40000 non-null  float64
 44  platform_avg_launch_price_usd       40000 non-null  float64
 45  platform_pct_online_multiplayer     40000 non-null  float64
 46  genre_titles                        40000 non-null  int64
 47  genre_avg_revenue                   40000 non-null  float64
 48  genre_avg_metacritic_score          39999 non-null  float64
 49  genre_avg_user_score                40000 non-null  float64
 50  genre_avg_launch_price_usd          40000 non-null  float64
 51  genre_pct_online_multiplayer        40000 non-null  float64
 52  genre_pct_dlc_released              40000 non-null  float64
 53  genre_pct_microtransactions         40000 non-null  float64
dtypes: float64(25), int64(16), str(13)
memory usage: 16.5 MB

In [47]:
leak_cols = [
    'publisher_avg_revenue',
    'platform_avg_revenue',
    'genre_avg_revenue'
]

train.drop(columns=leak_cols, inplace=True)

In [48]:
num_cols = train.select_dtypes(include=['int64','float64']).columns

for col in num_cols:
    train[col] = train[col].fillna(train[col].median())

In [49]:
cat_cols = train.select_dtypes(include='object').columns

for col in cat_cols:
    train[col] = train[col].fillna('Unknown')

/var/folders/2f/vs0p3bp12mvg2870k7c_rmr80000gn/T/ipykernel_85923/4239852025.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = train.select_dtypes(include='object').columns

In [50]:
train.isnull().sum()

game_id                               0
title                                 0
platform                              0
platform_type                         0
platform_maker                        0
platform_generation                   0
genre                                 0
year                                  0
publisher                             0
developer                             0
publisher_region                      0
publisher_tier                        0
esrb_rating                           0
metacritic_score                      0
user_score                            0
critic_review_count                   0
user_review_count                     0
estimated_revenue_million_usd         0
launch_price_usd                      0
is_sequel                             0
online_multiplayer                    0
dlc_released                          0
microtransactions                     0
loot_boxes                            0
game_pass_available                   0
vr_support                            0
goty_nominated                        0
goty_won                              0
how_long_to_beat_main_hrs             0
how_long_to_beat_completionist_hrs    0
publisher_is_developer                0
internal_build_id                     0
marketing_campaign_type               0
day_one_patch_size_mb                 0
publisher_titles                      0
publisher_avg_metacritic_score        0
publisher_avg_user_score              0
publisher_avg_launch_price_usd        0
publisher_pct_sequel                  0
platform_titles                       0
platform_avg_metacritic_score         0
platform_avg_user_score               0
platform_avg_launch_price_usd         0
platform_pct_online_multiplayer       0
genre_titles                          0
genre_avg_metacritic_score            0
genre_avg_user_score                  0
genre_avg_launch_price_usd            0
genre_pct_online_multiplayer          0
genre_pct_dlc_released                0
genre_pct_microtransactions           0
dtype: int64

In [51]:
for col in train.select_dtypes(include='object').columns:
    print(col, train[col].nunique())

game_id 40000
title 1389
platform 30
platform_type 7
platform_maker 8
genre 20
publisher 51
developer 51
publisher_region 15
publisher_tier 3
esrb_rating 6
internal_build_id 40000
marketing_campaign_type 4

/var/folders/2f/vs0p3bp12mvg2870k7c_rmr80000gn/T/ipykernel_85923/1385114367.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in train.select_dtypes(include='object').columns:

In [52]:
drop_cols = ["game_id","internal_build_id","title"]

In [53]:
train.drop(columns=drop_cols,inplace=True)

In [54]:
for col in train.select_dtypes(include='object').columns:
    print(col, train[col].nunique())

platform 30
platform_type 7
platform_maker 8
genre 20
publisher 51
developer 51
publisher_region 15
publisher_tier 3
esrb_rating 6
marketing_campaign_type 4

/var/folders/2f/vs0p3bp12mvg2870k7c_rmr80000gn/T/ipykernel_85923/1385114367.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in train.select_dtypes(include='object').columns:

In [55]:
train_backup = train.copy()

In [56]:
from sklearn.preprocessing import LabelEncoder

cat_cols = train.select_dtypes(include='object').columns

encoders = {}

for col in cat_cols:
    le = LabelEncoder()
    train[col] = le.fit_transform(train[col].astype(str))

    encoders[col] = le

/var/folders/2f/vs0p3bp12mvg2870k7c_rmr80000gn/T/ipykernel_85923/3219789622.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = train.select_dtypes(include='object').columns

In [57]:
train.select_dtypes(include='object').columns

Index([], dtype='str')

In [58]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 48 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   platform                            40000 non-null  int64
 1   platform_type                       40000 non-null  int64
 2   platform_maker                      40000 non-null  int64
 3   platform_generation                 40000 non-null  int64
 4   genre                               40000 non-null  int64
 5   year                                40000 non-null  int64
 6   publisher                           40000 non-null  int64
 7   developer                           40000 non-null  int64
 8   publisher_region                    40000 non-null  int64
 9   publisher_tier                      40000 non-null  int64
 10  esrb_rating                         40000 non-null  int64
 11  metacritic_score                    40000 non-null  float64
 12  user_score                          40000 non-null  float64
 13  critic_review_count                 40000 non-null  float64
 14  user_review_count                   40000 non-null  float64
 15  estimated_revenue_million_usd       40000 non-null  float64
 16  launch_price_usd                    40000 non-null  float64
 17  is_sequel                           40000 non-null  int64
 18  online_multiplayer                  40000 non-null  int64
 19  dlc_released                        40000 non-null  int64
 20  microtransactions                   40000 non-null  int64
 21  loot_boxes                          40000 non-null  int64
 22  game_pass_available                 40000 non-null  int64
 23  vr_support                          40000 non-null  int64
 24  goty_nominated                      40000 non-null  int64
 25  goty_won                            40000 non-null  int64
 26  how_long_to_beat_main_hrs           40000 non-null  float64
 27  how_long_to_beat_completionist_hrs  40000 non-null  float64
 28  publisher_is_developer              40000 non-null  int64
 29  marketing_campaign_type             40000 non-null  int64
 30  day_one_patch_size_mb               40000 non-null  int64
 31  publisher_titles                    40000 non-null  int64
 32  publisher_avg_metacritic_score      40000 non-null  float64
 33  publisher_avg_user_score            40000 non-null  float64
 34  publisher_avg_launch_price_usd      40000 non-null  float64
 35  publisher_pct_sequel                40000 non-null  float64
 36  platform_titles                     40000 non-null  int64
 37  platform_avg_metacritic_score       40000 non-null  float64
 38  platform_avg_user_score             40000 non-null  float64
 39  platform_avg_launch_price_usd       40000 non-null  float64
 40  platform_pct_online_multiplayer     40000 non-null  float64
 41  genre_titles                        40000 non-null  int64
 42  genre_avg_metacritic_score          40000 non-null  float64
 43  genre_avg_user_score                40000 non-null  float64
 44  genre_avg_launch_price_usd          40000 non-null  float64
 45  genre_pct_online_multiplayer        40000 non-null  float64
 46  genre_pct_dlc_released              40000 non-null  float64
 47  genre_pct_microtransactions         40000 non-null  float64
dtypes: float64(22), int64(26)
memory usage: 14.6 MB

In [59]:
train.head()

,platform,platform_type,platform_maker,platform_generation,genre,year,publisher,developer,publisher_region,publisher_tier,...,platform_avg_user_score,platform_avg_launch_price_usd,platform_pct_online_multiplayer,genre_titles,genre_avg_metacritic_score,genre_avg_user_score,genre_avg_launch_price_usd,genre_pct_online_multiplayer,genre_pct_dlc_released,genre_pct_microtransactions
0,0,1,1,2,2,1985,42,34,13,1,...,7.514181,59.705971,0.504667,1018,76.364855,7.651621,60.210118,0.337917,0.627701,0.233792
1,0,1,1,2,5,1985,29,25,8,1,...,7.514181,59.705971,0.504667,207,73.528988,7.404522,59.216965,0.338164,0.632850,0.256039
2,9,1,4,3,16,1985,18,2,8,1,...,7.419198,60.098635,0.523153,2339,70.982827,7.119449,60.065373,1.000000,0.639590,0.322788
3,9,1,4,3,12,1985,45,44,5,1,...,7.419198,60.098635,0.523153,1791,77.474991,7.745751,59.801496,0.288107,0.634841,0.248465
4,14,5,7,0,0,1985,29,29,8,1,...,7.417108,32.715224,0.510630,761,73.714104,7.409703,32.997056,0.295664,0.626807,0.231275

In [60]:
X = train.drop('estimated_revenue_million_usd', axis=1)
y = train['estimated_revenue_million_usd']

In [61]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [62]:
print(X_train.shape)
print(X_val.shape)

(32000, 47)
(8000, 47)

In [63]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42)

In [64]:
val_preds = rf.predict(X_val)

In [65]:
from sklearn.metrics import mean_squared_error
import numpy as np

rmse = np.sqrt(mean_squared_error(y_val, val_preds))
print("RMSE:", rmse)

RMSE: 782.4319956838855

In [66]:
from sklearn.metrics import r2_score

print("R2:", r2_score(y_val, val_preds))

R2: 0.38175771480421516

In [67]:
feature_importance = (
    pd.DataFrame({
        'feature': X.columns,
        'importance': rf.feature_importances_
    })
    .sort_values('importance', ascending=False)
)

feature_importance.head(20)

                               feature  importance
11                    metacritic_score    0.121923
40                        genre_titles    0.113493
30                    publisher_titles    0.057232
12                          user_score    0.051177
32            publisher_avg_user_score    0.047566
29               day_one_patch_size_mb    0.044896
31      publisher_avg_metacritic_score    0.041242
5                                 year    0.041087
15                    launch_price_usd    0.038409
43          genre_avg_launch_price_usd    0.037895
26  how_long_to_beat_completionist_hrs    0.034548
14                   user_review_count    0.034544
13                 critic_review_count    0.033707
25           how_long_to_beat_main_hrs    0.032420
7                            developer    0.022360
38       platform_avg_launch_price_usd    0.022292
34                publisher_pct_sequel    0.019859
16                           is_sequel    0.019093
33      publisher_avg_launch_price_usd    0.016136
44        genre_pct_online_multiplayer    0.014878

## Preprocessing Test_DF

In [68]:
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 33 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   game_id                             10000 non-null  str
 1   title                               10000 non-null  str
 2   platform                            10000 non-null  str
 3   platform_type                       10000 non-null  str
 4   platform_maker                      10000 non-null  str
 5   platform_generation                 10000 non-null  int64
 6   genre                               10000 non-null  str
 7   year                                10000 non-null  int64
 8   publisher                           10000 non-null  str
 9   developer                           10000 non-null  str
 10  publisher_region                    10000 non-null  str
 11  publisher_tier                      10000 non-null  str
 12  esrb_rating                         10000 non-null  str
 13  metacritic_score                    8500 non-null   float64
 14  user_score                          10000 non-null  float64
 15  critic_review_count                 8500 non-null   float64
 16  user_review_count                   8500 non-null   float64
 17  launch_price_usd                    10000 non-null  float64
 18  is_sequel                           10000 non-null  int64
 19  online_multiplayer                  10000 non-null  int64
 20  dlc_released                        10000 non-null  int64
 21  microtransactions                   10000 non-null  int64
 22  loot_boxes                          10000 non-null  int64
 23  game_pass_available                 10000 non-null  int64
 24  vr_support                          10000 non-null  int64
 25  goty_nominated                      10000 non-null  int64
 26  goty_won                            10000 non-null  int64
 27  how_long_to_beat_main_hrs           10000 non-null  float64
 28  how_long_to_beat_completionist_hrs  10000 non-null  float64
 29  publisher_is_developer              10000 non-null  int64
 30  internal_build_id                   10000 non-null  str
 31  marketing_campaign_type             7536 non-null   str
 32  day_one_patch_size_mb               10000 non-null  int64
dtypes: float64(7), int64(13), str(13)
memory usage: 2.5 MB

In [69]:
publisher_cols = [
    'publisher',
    'publisher_tier',
    'titles',
    'avg_metacritic_score',
    'avg_user_score',
    'avg_launch_price_usd',
    'pct_sequel'
]

test = test.merge(
    publisher[publisher_cols],
    on='publisher',
    how='left'
)

In [70]:
test.shape

(10000, 39)

In [71]:
platform_cols = [
    'platform',
    'platform_generation',
    'titles',
    'avg_metacritic_score',
    'avg_user_score',
    'avg_launch_price_usd',
    'pct_online_multiplayer'
]

test = test.merge(
    platform[platform_cols],
    on='platform',
    how='left'
)

In [72]:
genre_cols = [
    'genre',
    'platform_type',
    'titles',
    'avg_metacritic_score',
    'avg_user_score',
    'avg_launch_price_usd',
    'pct_online_multiplayer',
    'pct_dlc_released',
    'pct_microtransactions'
]

test = test.merge(
    genre[genre_cols],
    on=['genre', 'platform_type'],
    how='left'
)

In [73]:
test.shape

(10000, 52)

In [74]:
test.columns

Index(['game_id', 'title', 'platform', 'platform_type', 'platform_maker',
       'platform_generation_x', 'genre', 'year', 'publisher', 'developer',
       'publisher_region', 'publisher_tier_x', 'esrb_rating',
       'metacritic_score', 'user_score', 'critic_review_count',
       'user_review_count', 'launch_price_usd', 'is_sequel',
       'online_multiplayer', 'dlc_released', 'microtransactions', 'loot_boxes',
       'game_pass_available', 'vr_support', 'goty_nominated', 'goty_won',
       'how_long_to_beat_main_hrs', 'how_long_to_beat_completionist_hrs',
       'publisher_is_developer', 'internal_build_id',
       'marketing_campaign_type', 'day_one_patch_size_mb', 'publisher_tier_y',
       'titles_x', 'avg_metacritic_score_x', 'avg_user_score_x',
       'avg_launch_price_usd_x', 'pct_sequel', 'platform_generation_y',
       'titles_y', 'avg_metacritic_score_y', 'avg_user_score_y',
       'avg_launch_price_usd_y', 'pct_online_multiplayer_x', 'titles',
       'avg_metacritic_score', 'avg_user_score', 'avg_launch_price_usd',
       'pct_online_multiplayer_y', 'pct_dlc_released',
       'pct_microtransactions'],
      dtype='str')

In [75]:
rename_dict = {
    'platform_generation_x': 'publisher_platform_generation',
    'publisher_tier_x': 'publisher_tier',

    'titles_x': 'publisher_titles',
    'avg_metacritic_score_x': 'publisher_avg_metacritic_score',
    'avg_user_score_x': 'publisher_avg_user_score',
    'avg_launch_price_usd_x': 'publisher_avg_launch_price_usd',

    'platform_generation_y': 'platform_generation',
    'titles_y': 'platform_titles',
    'avg_metacritic_score_y': 'platform_avg_metacritic_score',
    'avg_user_score_y': 'platform_avg_user_score',
    'avg_launch_price_usd_y': 'platform_avg_launch_price_usd',
    'pct_online_multiplayer_x': 'platform_pct_online_multiplayer',

    'titles': 'genre_titles',
    'avg_metacritic_score': 'genre_avg_metacritic_score',
    'avg_user_score': 'genre_avg_user_score',
    'avg_launch_price_usd': 'genre_avg_launch_price_usd',
    'pct_online_multiplayer_y': 'genre_pct_online_multiplayer',
    'pct_dlc_released': 'genre_pct_dlc_released',
    'pct_microtransactions': 'genre_pct_microtransactions'
}

test.rename(columns=rename_dict, inplace=True)

In [76]:
test.columns

Index(['game_id', 'title', 'platform', 'platform_type', 'platform_maker',
       'publisher_platform_generation', 'genre', 'year', 'publisher',
       'developer', 'publisher_region', 'publisher_tier', 'esrb_rating',
       'metacritic_score', 'user_score', 'critic_review_count',
       'user_review_count', 'launch_price_usd', 'is_sequel',
       'online_multiplayer', 'dlc_released', 'microtransactions', 'loot_boxes',
       'game_pass_available', 'vr_support', 'goty_nominated', 'goty_won',
       'how_long_to_beat_main_hrs', 'how_long_to_beat_completionist_hrs',
       'publisher_is_developer', 'internal_build_id',
       'marketing_campaign_type', 'day_one_patch_size_mb', 'publisher_tier_y',
       'publisher_titles', 'publisher_avg_metacritic_score',
       'publisher_avg_user_score', 'publisher_avg_launch_price_usd',
       'pct_sequel', 'platform_generation', 'platform_titles',
       'platform_avg_metacritic_score', 'platform_avg_user_score',
       'platform_avg_launch_price_usd', 'platform_pct_online_multiplayer',
       'genre_titles', 'genre_avg_metacritic_score', 'genre_avg_user_score',
       'genre_avg_launch_price_usd', 'genre_pct_online_multiplayer',
       'genre_pct_dlc_released', 'genre_pct_microtransactions'],
      dtype='str')

In [77]:
set(X.columns) - set(test.columns)

{'publisher_pct_sequel'}

In [78]:
test.rename(
    columns={'pct_sequel': 'publisher_pct_sequel'},
    inplace=True
)

In [79]:
set(X.columns) - set(test.columns)

set()

In [80]:
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 52 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   game_id                             10000 non-null  str
 1   title                               10000 non-null  str
 2   platform                            10000 non-null  str
 3   platform_type                       10000 non-null  str
 4   platform_maker                      10000 non-null  str
 5   publisher_platform_generation       10000 non-null  int64
 6   genre                               10000 non-null  str
 7   year                                10000 non-null  int64
 8   publisher                           10000 non-null  str
 9   developer                           10000 non-null  str
 10  publisher_region                    10000 non-null  str
 11  publisher_tier                      10000 non-null  str
 12  esrb_rating                         10000 non-null  str
 13  metacritic_score                    8500 non-null   float64
 14  user_score                          10000 non-null  float64
 15  critic_review_count                 8500 non-null   float64
 16  user_review_count                   8500 non-null   float64
 17  launch_price_usd                    10000 non-null  float64
 18  is_sequel                           10000 non-null  int64
 19  online_multiplayer                  10000 non-null  int64
 20  dlc_released                        10000 non-null  int64
 21  microtransactions                   10000 non-null  int64
 22  loot_boxes                          10000 non-null  int64
 23  game_pass_available                 10000 non-null  int64
 24  vr_support                          10000 non-null  int64
 25  goty_nominated                      10000 non-null  int64
 26  goty_won                            10000 non-null  int64
 27  how_long_to_beat_main_hrs           10000 non-null  float64
 28  how_long_to_beat_completionist_hrs  10000 non-null  float64
 29  publisher_is_developer              10000 non-null  int64
 30  internal_build_id                   10000 non-null  str
 31  marketing_campaign_type             7536 non-null   str
 32  day_one_patch_size_mb               10000 non-null  int64
 33  publisher_tier_y                    10000 non-null  str
 34  publisher_titles                    10000 non-null  int64
 35  publisher_avg_metacritic_score      10000 non-null  float64
 36  publisher_avg_user_score            10000 non-null  float64
 37  publisher_avg_launch_price_usd      10000 non-null  float64
 38  publisher_pct_sequel                10000 non-null  float64
 39  platform_generation                 7074 non-null   float64
 40  platform_titles                     7074 non-null   float64
 41  platform_avg_metacritic_score       7074 non-null   float64
 42  platform_avg_user_score             7074 non-null   float64
 43  platform_avg_launch_price_usd       7074 non-null   float64
 44  platform_pct_online_multiplayer     7074 non-null   float64
 45  genre_titles                        9982 non-null   float64
 46  genre_avg_metacritic_score          9976 non-null   float64
 47  genre_avg_user_score                9982 non-null   float64
 48  genre_avg_launch_price_usd          9982 non-null   float64
 49  genre_pct_online_multiplayer        9982 non-null   float64
 50  genre_pct_dlc_released              9982 non-null   float64
 51  genre_pct_microtransactions         9982 non-null   float64
dtypes: float64(24), int64(14), str(14)
memory usage: 4.0 MB

In [81]:
num_cols = [col for col in train.select_dtypes(include=['int64','float64']).columns
            if col in test.columns]

cat_cols = [col for col in train.select_dtypes(include='object').columns
            if col in test.columns]

for col in num_cols:
    test[col] = test[col].fillna(train[col].median())

for col in cat_cols:
    test[col] = test[col].fillna(train[col].mode()[0])

In [82]:
test.isnull().sum().sort_values(ascending=False).head()

game_id                               0
title                                 0
how_long_to_beat_completionist_hrs    0
publisher_is_developer                0
internal_build_id                     0
dtype: int64

In [83]:
for col in test.select_dtypes(include='object').columns:
    print(col, test[col].nunique())

game_id 10000
title 1270
platform 13
platform_type 7
platform_maker 6
genre 20
publisher 51
developer 51
publisher_region 15
publisher_tier 3
esrb_rating 6
internal_build_id 10000
marketing_campaign_type 4
publisher_tier_y 3

/var/folders/2f/vs0p3bp12mvg2870k7c_rmr80000gn/T/ipykernel_85923/3892140649.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in test.select_dtypes(include='object').columns:

In [84]:
test_ids = test["game_id"].copy()

In [85]:
drop_cols = [
    'game_id',
    'title',
    'internal_build_id'
]
test.drop(columns=drop_cols, inplace=True)

In [86]:
'publisher_tier_y' in X.columns

False

In [87]:
test.drop(columns=['publisher_tier_y'], inplace=True)

In [88]:
for col in test.select_dtypes(include='object').columns:
    print(col, test[col].nunique())

platform 13
platform_type 7
platform_maker 6
genre 20
publisher 51
developer 51
publisher_region 15
publisher_tier 3
esrb_rating 6
marketing_campaign_type 4

/var/folders/2f/vs0p3bp12mvg2870k7c_rmr80000gn/T/ipykernel_85923/3892140649.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in test.select_dtypes(include='object').columns:

In [89]:
test.shape

(10000, 48)

In [90]:
for col in encoders:
    test[col] = test[col].astype(str)

    unseen = ~test[col].isin(encoders[col].classes_)

    if unseen.any():
        test.loc[unseen, col] = encoders[col].classes_[0]

    test[col] = encoders[col].transform(test[col])

In [91]:
test.select_dtypes(include='object').columns

Index([], dtype='str')

In [92]:
test = test[X.columns]

In [93]:
print(set(test.columns) - set(X.columns))
print(set(X.columns) - set(test.columns))

set()
set()

In [94]:
test_pred = rf.predict(test)

In [95]:
test_pred[:10]

array([2.79216500e+01, 3.35146500e+01, 8.66051000e+01, 6.10300000e-01,
       1.43071600e+02, 3.64174200e+02, 3.06623785e+03, 2.51888545e+03,
       1.21774270e+03, 4.35994250e+02])

In [96]:
submission = pd.DataFrame({
    'game_id': test_ids,
    'estimated_revenue_million_usd': test_pred
})

In [97]:
submission.shape

(10000, 2)

In [98]:
submission.head()

   game_id  estimated_revenue_million_usd
0  G016973                       27.92165
1  G011036                       33.51465
2  G000593                       86.60510
3  G013281                        0.61030
4  G004160                      143.07160

In [99]:
submission.to_csv('submission.csv', index=False)